### ISSUE TITLE
Cannot compile (again) - gfx-backend-metal build.rs error, target x86_64-pc-windows-msvc

### ISSUE THREAD

**Issue by clemarescx** [amethyst/space-menace#27]
Hi,
I would like to report the same bug as for my previous issue #9, in spite of setting the features flag correctly in the `Cargo.toml`: 
```toml
#...

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst", features = ["nightly","vulkan", "json"] }
#...
```
Here's the backtrace - the only difference with that of #9 is that `gfx-backend-metal` is v0.2.3 instead of v0.2.1
```powershell

error: failed to run custom build command for `gfx-backend-metal v0.2.3`

Caused by:
  process didn't exit successfully: `C:\Work\GitRepos\space-menace\target\debug\build\gfx-backend-metal-d9da2542148691d8\build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'unsupported target x86_64-pc-windows-msvc', C:\Users\YourMum\.cargo\registry\src\github.com-1ecc6299db9ec823\gfx-backend-metal-0.2.3\build.rs:17:9
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.29\src\backtrace\mod.rs:66
   1: std::sys_common::backtrace::_print
             at /rustc/c798dffac9dc8c82374db48f5b474690cc6e9686\/src\libstd\sys_common\backtrace.rs:47
   2: std::sys_common::backtrace::print
             at /rustc/c798dffac9dc8c82374db48f5b474690cc6e9686\/src\libstd\sys_common\backtrace.rs:36
   3: std::panicking::default_hook::{{closure}}
             at /rustc/c798dffac9dc8c82374db48f5b474690cc6e9686\/src\libstd\panicking.rs:200
   4: std::panicking::default_hook
             at /rustc/c798dffac9dc8c82374db48f5b474690cc6e9686\/src\libstd\panicking.rs:214
   5: std::panicking::rust_panic_with_hook
             at /rustc/c798dffac9dc8c82374db48f5b474690cc6e9686\/src\libstd\panicking.rs:477
   6: std::panicking::continue_panic_fmt
             at /rustc/c798dffac9dc8c82374db48f5b474690cc6e9686\/src\libstd\panicking.rs:384rs:384
   7: std::panicking::begin_panic_fmt                                                 rs:339
             at /rustc/c798dffac9dc8c82374db48f5b474690cc6e9686\/src\libstd\panicking.rs:339
   8: build_script_build::main
             at .\build.rs:17
   9: std::rt::lang_start::{{closure}}<()>
             at /rustc/c798dffac9dc8c82374db48f5b474690cc6e9686\src\libstd\rt.rs:64
  10: std::rt::lang_start_internal::{{closure}}
             at /rustc/c798dffac9dc8c82374db48f5b474690cc6e9686\/src\libstd\rt.rs:49  rs:296
  11: std::panicking::try::do_call<closure,i32>
             at /rustc/c798dffac9dc8c82374db48f5b474690cc6e9686\/src\libstd\panicking.ib.rs:82rs:296
  12: panic_unwind::__rust_maybe_catch_panic                                          rs:275
             at /rustc/c798dffac9dc8c82374db48f5b474690cc6e9686\/src\libpanic_unwind\lib.rs:82                                                                              94
  13: std::panicking::try
             at /rustc/c798dffac9dc8c82374db48f5b474690cc6e9686\/src\libstd\panicking.rs:275
  14: std::panic::catch_unwind
             at /rustc/c798dffac9dc8c82374db48f5b474690cc6e9686\/src\libstd\panic.rs:394
  15: std::rt::lang_start_internal                                                    l:78
             at /rustc/c798dffac9dc8c82374db48f5b474690cc6e9686\/src\libstd\rt.rs:48
  16: std::rt::lang_start<()>
             at /rustc/c798dffac9dc8c82374db48f5b474690cc6e9686\src\libstd\rt.rs:64
  17: main
  18: invoke_main
             at d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78  19: __scrt_common_main_seh
             at d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  20: BaseThreadInitThunk  21: RtlUserThreadStart

warning: build failed, waiting for other jobs to finish...
error: build failed
```
I also tried on stable and without `release`, but no cigar. This must be due to recent changes, because I managed to compile and run it when issue #9 was closed.

**Comment by clemarescx** [comment]
Alright I found out where it came from: in the `Cargo.toml` file, adding `"vulkan"` to the array of features for the `amethyst` crate does not override the default set in the `[features]` section.
I fixed it by setting the default to `["vulkan"]`:
```toml
# Cargo.toml
[package]
name = "space-menace"
version = "0.1.0"
authors = ["Kumar Ankur <kmrankur@outlook.com>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst", features = ["nightly", "json"] }
serde = "*"
log = "*"
specs-derive = "*"

[features]
default = ["vulkan"] # <---- ta-dah!
metal = ["amethyst/metal"]
vulkan = ["amethyst/vulkan"]
```
